/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#87948a",
        "on-primary-fixed-variant": "#005232",
        "on-surface-variant": "#bccabf",
        "secondary-fixed": "#dae8be",
        "tertiary-fixed-dim": "#aad0ad",
        "secondary-fixed-dim": "#becca3",
        "primary-fixed-dim": "#63dd9f",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#131e19",
        "on-primary-fixed": "#002111",
        "on-secondary-fixed-variant": "#3f4b2c",
        "tertiary-fixed": "#c6ecc8",
        "surface-variant": "#2c3731",
        "tertiary": "#d0f7d2",
        "on-tertiary-fixed-variant": "#2d4e33",
        "primary-fixed": "#81fab9",
        "surface-container-high": "#212c27",
        "on-secondary-fixed": "#141f05",
        "inverse-primary": "#006d44",
        "on-error": "#690005",
        "background": "#0b1611",
        "error-container": "#93000a",
        "primary": "#a9ffcc",
        "surface-container": "#17221d",
        "on-primary-container": "#006640",
        "primary-container": "#6ee7a8",
        "inverse-surface": "#d9e6dd",
        "tertiary-container": "#b4dab7",
        "on-primary": "#003921",
        "secondary-container": "#414d2e",
        "error": "#ffb4ab",
        "surface": "#0b1611",
        "secondary": "#becca3",
        "on-secondary": "#293417",
        "surface-container-lowest": "#06100b",
        "inverse-on-surface": "#28332d",
        "on-tertiary": "#16371f",
        "on-tertiary-container": "#3f6145",
        "outline-variant": "#3d4a41",
        "on-tertiary-fixed": "#00210b",
        "surface-bright": "#303c36",
        "surface-container-highest": "#2c3731",
        "on-background": "#d9e6dd",
        "on-secondary-container": "#b0be96",
        "surface-tint": "#63dd9f",
        "surface-dim": "#0b1611",
        "on-surface": "#d9e6dd"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
